image:
  file: .gitpod.Dockerfile

tasks:
  - init: >
      python setup.py build &&
      pip install -r requirements.txt
      cd testapp &&
      pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py shell -c "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'adminpass')" &&
      pytest
    name: setup
