image:
  file: .gitpod.Dockerfile

tasks:
  - init: >
      python setup.py build &&
      pip install -r requirements.txt
      cd testapp &&
      pip install -r requirements.txt &&
      python manage.py migrate &&
      echo "from django.contrib.auth import get_user_model; get_user_model().objects.create_superuser('admin', '', 'changeme')" | python3 manage.py shell &&
      pytest
    name: setup
