# Generated by Django 2.0.9 on 2019-01-19 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailnhsstyle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='X',
            fields=[
                ('headersettings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailnhsstyle.HeaderSettings')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailnhsstyle.headersettings',),
        ),
    ]
