# Generated by Django 3.1.7 on 2021-03-16 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailnhsukfrontendsettings", "0005_remove_emergency_alert"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footersettings",
            name="fixed_coloumn_footer",
        ),
    ]
