# Generated by Django 2.1.15 on 2020-04-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailnhsukfrontendsettings', '0005_remove_emergency_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='logo_custom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='organisation_descriptor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='organisation_white',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='organisational',
            field=models.BooleanField(default=False),
        ),
    ]
