# Generated by Django 3.1.5 on 2021-01-31 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailnhsukfrontendsettings', '0005_remove_emergency_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlinks',
            name='internal_page',
            field=models.ForeignKey(blank=True, help_text='If you are not adding an external URL choose a page to link to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='footerlinks',
            name='link_label',
            field=models.CharField(blank=True, help_text='Link label is required is you enter a link url but is optional if you choose a page below', max_length=250),
        ),
        migrations.AlterField(
            model_name='footerlinks',
            name='link_url',
            field=models.URLField(blank=True, help_text='If you add a link url then also ad the text for the link below'),
        ),
    ]
