# Generated by Django 3.1.8 on 2021-05-20 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0023_add_choose_permissions"),
        (
            "wagtailnhsukfrontendsettings",
            "0006_remove_footersettings_fixed_coloumn_footer",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="headersettings",
            name="logo_custom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="headersettings",
            name="organisation_descriptor",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="headersettings",
            name="organisation_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="headersettings",
            name="organisation_split_name",
            field=models.CharField(
                blank=True,
                help_text="Some NHS organisations’ names are too long to fit onto a single line and they have to run onto two lines. You should use discretion to decide where best to split your name depending on what makes most sense and what looks visually balanced.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="headersettings",
            name="organisation_white",
            field=models.BooleanField(
                default=False,
                help_text="Organisational header with a white background variant.",
            ),
        ),
    ]
