# Generated by Django 2.0.9 on 2018-10-22 10:56

from django.db import migrations
import wagtail.core.fields
import wagtailnhsstyle.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('callout', wagtailnhsstyle.blocks.CalloutBlock())], default=[]),
            preserve_default=False,
        ),
    ]
