# Generated by Django 2.0.9 on 2019-01-22 14:05

import django.db.models.deletion
import wagtail.blocks as wagtail_blocks
import wagtail.blocks.field_block as wagtail_field_block
import wagtail.fields as wagtail_fields
import wagtail.images.blocks
from django.db import migrations, models

import wagtailnhsukfrontend.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0040_page_draft_title"),
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail_fields.StreamField(
                [
                    (
                        "action_link",
                        wagtail_blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail_blocks.CharBlock(
                                        label="link text", required=True
                                    ),
                                ),
                                (
                                    "external_url",
                                    wagtail_blocks.URLBlock(
                                        label="external URL", required=True
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "care_card",
                        wagtail_blocks.StructBlock(
                            [
                                (
                                    "type",
                                    wagtail_blocks.ChoiceBlock(
                                        choices=[
                                            ("primary", "Primary"),
                                            ("urgent", "Urgent"),
                                            ("immediate", "Immediate"),
                                        ]
                                    ),
                                ),
                                ("title", wagtail_blocks.CharBlock(required=True)),
                                ("body", wagtail_blocks.RichTextBlock(required=True)),
                            ]
                        ),
                    ),
                    (
                        "details",
                        wagtail_blocks.StructBlock(
                            [
                                ("title", wagtail_blocks.CharBlock(required=True)),
                                ("body", wagtail_blocks.RichTextBlock(required=True)),
                            ]
                        ),
                    ),
                    (
                        "do_list",
                        wagtail_blocks.StructBlock(
                            [
                                (
                                    "do",
                                    wagtail_blocks.ListBlock(
                                        wagtail_field_block.RichTextBlock
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "dont_list",
                        wagtail_blocks.StructBlock(
                            [
                                (
                                    "dont",
                                    wagtail_blocks.ListBlock(
                                        wagtail_field_block.RichTextBlock
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "expander",
                        wagtail_blocks.StructBlock(
                            [
                                ("title", wagtail_blocks.CharBlock(required=True)),
                                ("body", wagtail_blocks.RichTextBlock(required=True)),
                            ]
                        ),
                    ),
                    (
                        "expander_group",
                        wagtail_blocks.StructBlock(
                            [
                                (
                                    "expanders",
                                    wagtail_blocks.ListBlock(
                                        wagtailnhsukfrontend.blocks.ExpanderBlock
                                    ),
                                )
                            ]
                        ),
                    ),
                    ("inset_text", wagtailnhsukfrontend.blocks.InsetTextBlock()),
                    (
                        "image",
                        wagtail_blocks.StructBlock(
                            [
                                (
                                    "content_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=True
                                    ),
                                ),
                                (
                                    "alt_text",
                                    wagtail_blocks.CharBlock(
                                        help_text="Only leave this blank if the image is decorative.",
                                        required=False,
                                    ),
                                ),
                                ("caption", wagtail_blocks.CharBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        "panel",
                        wagtail_blocks.StructBlock(
                            [
                                (
                                    "labeled_title",
                                    wagtail_blocks.CharBlock(required=False),
                                ),
                                ("body", wagtail_blocks.RichTextBlock(required=True)),
                            ]
                        ),
                    ),
                    (
                        "warning_callout",
                        wagtailnhsukfrontend.blocks.WarningCalloutBlock(),
                    ),
                ]
            ),
            preserve_default=False,
        ),
    ]
