# Generated by Django 2.0.9 on 2018-11-26 08:43

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtailnhsstyle.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('action_link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(label='link text', required=True)), ('external_url', wagtail.core.blocks.URLBlock(label='external URL', required=True))])), ('callout', wagtailnhsstyle.blocks.CalloutBlock())]),
        ),
    ]
