# Generated by Django 2.0.9 on 2019-01-16 21:55

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtailnhsstyle.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_childpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('action_link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(label='link text', required=True)), ('external_url', wagtail.core.blocks.URLBlock(label='external URL', required=True))])), ('callout', wagtailnhsstyle.blocks.CalloutBlock()), ('care_card', wagtail.core.blocks.StructBlock([('type', wagtail.core.blocks.ChoiceBlock(choices=[('primary', 'Primary'), ('urgent', 'Urgent'), ('emergency', 'Emergency')])), ('title', wagtail.core.blocks.CharBlock(required=True)), ('body', wagtail.core.blocks.RichTextBlock(required=True))]))]),
        ),
    ]
