# Generated by Django 2.0.10 on 2019-04-10 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0021_image_file_hash"),
        ("home", "0005_review_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hero_heading",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
