# Generated by Django 2.1.8 on 2019-04-30 11:01

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_testformpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testformpage',
            name='body',
            field=wagtail.core.fields.StreamField([('input', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock(required=True)), ('hint', wagtail.core.blocks.CharBlock(required=False)), ('name', wagtail.core.blocks.RegexBlock(error_messages={'invalid': 'Valid characters: A-Z, a-z, 0-9, - and _'}, regex='^[A-Za-z0-9-_]+$', required=False)), ('required', wagtail.core.blocks.BooleanBlock(default=True, required=False)), ('disabled', wagtail.core.blocks.BooleanBlock(default=False, required=False)), ('validator', wagtail.core.blocks.CharBlock(required=False)), ('missing_field_error_message', wagtail.core.blocks.CharBlock(default='This field is required', required=False)), ('validation_error_message', wagtail.core.blocks.CharBlock(default='Validation error', required=False)), ('width', wagtail.core.blocks.ChoiceBlock(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('10', '10'), ('20', '20')], required=False))])), ('action_link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(label='Link text', required=True)), ('external_url', wagtail.core.blocks.URLBlock(label='URL', required=True)), ('new_window', wagtail.core.blocks.BooleanBlock(label='Open in new window', required=False))]))], default=[]),
        ),
    ]
